version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     docker: 24
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $dockerhub_username -p $dockerhub_password
      - REPOSITORY_URI=$ecr_uri
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose --file=docker-compose.yml build
      # - docker build -t $REPOSITORY_URI:latest .
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $aws_region | docker login --username AWS --password-stdin $aws_account_id
      - echo Pushing the Docker images...
      - docker-compose --file=docker-compose.yml push
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      # - echo Writing image definitions file...
# artifacts:
#   files:
#     - docker-compose.yml
